name: test
permissions:
  contents: read
  id-token: write
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@6.0.2
      - uses: DeterminateSystems/nix-installer-action@21
      - uses: DeterminateSystems/magic-nix-cache-action@13
      - run: nix develop --command bats tests/
